sudo: required

language: generic

os:
  - linux
  - osx

env:
  - MYUSEMC=true MYPYTHON_VERSION=2.7
  - MYUSEMC=true MYPYTHON_VERSION=3.4
  - MYUSEMC=true MYPYTHON_VERSION=3.5
  - MYUSEMC=true MYPYTHON_VERSION=3.6
  - MYUSEMC=false

git:
  depth: 999999

branches:
  except:
    - /^v[0-9]/

before_install:
  - MYNAME=diffpy.srreal
  - umask 022
  - git fetch origin --tags
  - MYPYTHON=python; MYPIP=pip
  - NOSYS=true; NOAPT=true; NOBREW=true; NOMC=true
  - if ${MYUSEMC}; then
        NOMC=false;
    elif [[ ${TRAVIS_OS_NAME} == linux ]]; then
        NOAPT=false; NOSYS=false;
        MYPIPFLAGS="--user";
    elif [[ ${TRAVIS_OS_NAME} == osx ]]; then
        NOBREW=false; NOSYS=false;
        MYPYTHON=python3;
        MYPIP=pip3;
        MYPIPFLAGS="--user";
    fi
  - MYMCREPO=https://repo.continuum.io/miniconda
  - case ${TRAVIS_OS_NAME} in
    linux)
        MYMCBUNDLE=Miniconda2-latest-Linux-x86_64.sh ;;
    osx)
        MYMCBUNDLE=Miniconda2-latest-MacOSX-x86_64.sh ;;
    *)
        echo "Unsupported operating system." >&2;
        exit 2 ;;
    esac
  - MYRUNDIR=${PWD}/build/rundir

  - mkdir -p ~/pkgs/
  - mkdir -p ${MYRUNDIR}
  - cp .coveragerc ${MYRUNDIR}/

  - $NOMC || pushd ~/pkgs/
  - $NOMC || wget --timestamping ${MYMCREPO}/${MYMCBUNDLE}
  - $NOMC || test -x ~/mc/bin/conda || bash ${MYMCBUNDLE} -b -f -p ~/mc
  - $NOMC || popd
  - $NOMC || source ~/mc/bin/activate root
  - $NOMC || conda update --yes conda
  - $NOMC || conda install --yes conda-build jinja2 scons numpy
  # Make scons available globally.
  - $NOMC || mkdir -p ~/bin
  - $NOMC || cp ~/mc/bin/scons ~/bin/
  - $NOMC || conda create --name=testenv --yes python=${MYPYTHON_VERSION} coverage
  - $NOMC || conda config --add channels diffpy
  # FIXME - keep just the "diffpy" channel for public release.
  - $NOMC || conda config --add channels diffpy/channel/dev

  - $NOAPT || test "${TRAVIS_OS_NAME}" = "linux" || exit $?
  - $NOAPT || sudo apt-get update -qq
  - $NOAPT || sudo apt-get install -y
                  libgsl0-dev libboost-all-dev python-dev
                  python-setuptools python-numpy python-pyparsing
                  python-lxml python-pip build-essential scons

  - $NOBREW || test "${TRAVIS_OS_NAME}" = "osx" || exit $?
  - $NOBREW || brew update
  - $NOBREW || brew install gsl
  - $NOBREW || brew install scons
  - $NOBREW || brew install python3
  - $NOBREW || brew install boost-python --with-python3
  - $NOBREW || brew install numpy --without-python --with-python3

  - $NOSYS || devutils/makesdist
  - $NOSYS || MYTARBUNDLE="$(ls -t "${PWD}"/dist/*.tar.gz | head -1)"
  - $NOSYS || pushd ~/pkgs
  - $NOSYS || git clone https://github.com/diffpy/libObjCryst.git
  - $NOSYS || git clone https://github.com/diffpy/libdiffpy.git
  - $NOSYS || popd

install:
  - $NOMC || conda build --python=${MYPYTHON_VERSION} --dirty conda-recipe
  - $NOMC || MYCONDATESTENV="$(ls -td ~/mc/conda-bld/${MYNAME}_*/_t_env* | head -1)"
  - $NOMC || source activate ${MYCONDATESTENV:?"conda test environment not found"}
  - $NOMC || conda list  --export ${MYNAME} > /tmp/mypackage.txt
  - $NOMC || source activate testenv
  - $NOMC || conda install --yes --use-local --file=/tmp/mypackage.txt

  - $NOAPT || $MYPIP install $MYPIPFLAGS coverage
  - $NOAPT || $MYPIP install $MYPIPFLAGS periodictable
  # TODO - remove after fixup release of PyCifRW following 4.3.
  - $NOAPT || $MYPIP install $MYPIPFLAGS "pycifrw==4.2.1"
  - $NOAPT || $MYPIP install $MYPIPFLAGS diffpy.structure
  - $NOAPT || sudo scons -C ~/pkgs/libObjCryst install
  - $NOAPT || $MYPIP install $MYPIPFLAGS pyobjcryst
  - $NOAPT || sudo scons -C ~/pkgs/libdiffpy install
  - $NOAPT || $MYPIP install $MYPIPFLAGS "${MYTARBUNDLE}"

  - $NOBREW || $MYPIP install $MYPIPFLAGS coverage
  - $NOBREW || $MYPIP install $MYPIPFLAGS periodictable
  - $NOBREW || $MYPIP install $MYPIPFLAGS pycifrw
  # install diffpy.structure from the python3 development branch.
  # TODO - replace with PyPI version later.
  - $NOBREW || $MYPIP install $MYPIPFLAGS https://github.com/diffpy/diffpy.structure/archive/python3.tar.gz
  - $NOBREW || scons -C ~/pkgs/libObjCryst install
  - $NOBREW || $MYPIP install $MYPIPFLAGS pyobjcryst
  - $NOBREW || scons -C ~/pkgs/libdiffpy install
  - $NOBREW || $MYPIP install $MYPIPFLAGS "${MYTARBUNDLE}"

  - cd ${MYRUNDIR}
  - MYGIT_REV=$($MYPYTHON -c "import ${MYNAME}.version as v; print(v.__gitsha__)")
  - if [[ "${TRAVIS_COMMIT}" != "${MYGIT_REV}" ]]; then
        echo "Version mismatch ${TRAVIS_COMMIT} vs ${MYGIT_REV}.";
        exit 1;
    fi

before_script:
  - $NOBREW || USER_BASE="$(python3 -c 'import site; print(site.USER_BASE)')"
  - $NOBREW || PATH="${USER_BASE}/bin:${PATH}"

script:
  - coverage run --source ${MYNAME} -m ${MYNAME}.tests.run

after_success:
  - $MYPIP install $MYPIPFLAGS codecov
  - codecov
