{% set setupdata = load_setup_py_data() %}

package:
  name: diffpy.srreal
  version: {{ setupdata['version'] }}

source:
  # git_url: https://github.com/diffpy/diffpy.srreal
  git_url: ..

build:
  preserve_egg_dir: True        # [py2k]

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - setuptools
    - scons
    - numpy {{ numpy }}
    - libdiffpy {{ libdiffpy }}
    - pycifrw
    - diffpy.structure
    - boost {{ boost }}

  run:
    # NOTE libdiffpy is added implicitly from libdiffpy run_exports
    - python
    - setuptools
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x') }}
    - boost
    - pycifrw
    - diffpy.structure
    - pyobjcryst 2.0*
    - periodictable

test:
  # Python imports
  imports:
    - diffpy
    - diffpy.srreal
    - diffpy.srreal.tests

  commands:
    # Test if any module can be imported as the first one.
    - python -s -c "import diffpy.srreal.atomradiitable"
    - python -s -c "import diffpy.srreal.attributes"
    - python -s -c "import diffpy.srreal.bondcalculator"
    - python -s -c "import diffpy.srreal.bvparameterstable"
    - python -s -c "import diffpy.srreal.bvscalculator"
    - python -s -c "import diffpy.srreal.eventticker"
    - python -s -c "import diffpy.srreal.overlapcalculator"
    - python -s -c "import diffpy.srreal.pairquantity"
    - python -s -c "import diffpy.srreal.pdfbaseline"
    - python -s -c "import diffpy.srreal.pdfcalculator"
    - python -s -c "import diffpy.srreal.pdfenvelope"
    - python -s -c "import diffpy.srreal.peakprofile"
    - python -s -c "import diffpy.srreal.peakwidthmodel"
    - python -s -c "import diffpy.srreal.scatteringfactortable"
    - python -s -c "import diffpy.srreal.srreal_ext"
    - python -s -c "import diffpy.srreal.structureadapter"
    - python -s -c "import diffpy.srreal.structureconverters"
    - python -s -c "import diffpy.srreal.version"


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/diffpy/diffpy.srreal
  summary: Calculators for PDF, bond valence sum and other
    pair-interaction quantities.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
